### 各个环节统一配置文件
# 服务端口号
server:
  port: 8082
# 公共配置
spring:
  profiles:
    # 制定激活的配置文件application-xxx.yml
    active: dev
# <!-- knife4j 接入STEP ③：配置文件开启Knife4j -->
knife4j:
  # 为了生产环境接口安全,需要屏蔽所有Swagger的相关资源,生产环境设置为true
  production: true
  enable: true
  setting:
    # 开启器分组，让@ApiSort(int序号)控制controller排序展示
    enableGroup: true
